-- Form definitions are stored in the existing public.form_schemas table.
-- This migration is intentionally a no-op so it cannot create a duplicate
-- legacy duplicate table or overwrite the imported JSON definitions.
