/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppEmailRouteImport } from './routes/_app.email'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCountriesRouteImport } from './routes/_app.countries'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppVisaApprovalsRouteImport } from './routes/_app.visa.approvals'
import { Route as AppVisaApplicationsRouteImport } from './routes/_app.visa.applications'
import { Route as AppTasksWorkflowsRouteImport } from './routes/_app.tasks.workflows'
import { Route as AppTasksBoardRouteImport } from './routes/_app.tasks.board'
import { Route as AppTasksApprovalsRouteImport } from './routes/_app.tasks.approvals'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app.settings.security'
import { Route as AppSettingsRolesRouteImport } from './routes/_app.settings.roles'
import { Route as AppSettingsAuditRouteImport } from './routes/_app.settings.audit'
import { Route as AppSettingsApiRouteImport } from './routes/_app.settings.api'
import { Route as AppHrPayrollRouteImport } from './routes/_app.hr.payroll'
import { Route as AppHrLeaveRouteImport } from './routes/_app.hr.leave'
import { Route as AppHrEmployeesRouteImport } from './routes/_app.hr.employees'
import { Route as AppHrDepartmentsRouteImport } from './routes/_app.hr.departments'
import { Route as AppHrAttendanceRouteImport } from './routes/_app.hr.attendance'
import { Route as AppFinanceTransactionsRouteImport } from './routes/_app.finance.transactions'
import { Route as AppFinancePaymentsRouteImport } from './routes/_app.finance.payments'
import { Route as AppFinanceInvoicesRouteImport } from './routes/_app.finance.invoices'
import { Route as AppFinanceExpensesRouteImport } from './routes/_app.finance.expenses'
import { Route as AppDashboardHrRouteImport } from './routes/_app.dashboard.hr'
import { Route as AppDashboardFinanceRouteImport } from './routes/_app.dashboard.finance'
import { Route as AppDashboardEmployeeRouteImport } from './routes/_app.dashboard.employee'
import { Route as AppDashboardCrmRouteImport } from './routes/_app.dashboard.crm'
import { Route as AppCrmTasksRouteImport } from './routes/_app.crm.tasks'
import { Route as AppCrmPipelineRouteImport } from './routes/_app.crm.pipeline'
import { Route as AppCrmLeadsRouteImport } from './routes/_app.crm.leads'
import { Route as AppCrmCustomersRouteImport } from './routes/_app.crm.customers'
import { Route as AppCountriesCategoriesRouteImport } from './routes/_app.countries.categories'
import { Route as AppVisaApplicationsNewRouteImport } from './routes/_app.visa.applications.new'
import { Route as AppVisaApplicationsIdRouteImport } from './routes/_app.visa.applications.$id'

const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCountriesRoute = AppCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppVisaApprovalsRoute = AppVisaApprovalsRouteImport.update({
  id: '/visa/approvals',
  path: '/visa/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppVisaApplicationsRoute = AppVisaApplicationsRouteImport.update({
  id: '/visa/applications',
  path: '/visa/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksWorkflowsRoute = AppTasksWorkflowsRouteImport.update({
  id: '/tasks/workflows',
  path: '/tasks/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksBoardRoute = AppTasksBoardRouteImport.update({
  id: '/tasks/board',
  path: '/tasks/board',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksApprovalsRoute = AppTasksApprovalsRouteImport.update({
  id: '/tasks/approvals',
  path: '/tasks/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsApiRoute = AppSettingsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppHrPayrollRoute = AppHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppHrLeaveRoute = AppHrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppHrEmployeesRoute = AppHrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppHrDepartmentsRoute = AppHrDepartmentsRouteImport.update({
  id: '/hr/departments',
  path: '/hr/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppHrAttendanceRoute = AppHrAttendanceRouteImport.update({
  id: '/hr/attendance',
  path: '/hr/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceTransactionsRoute = AppFinanceTransactionsRouteImport.update({
  id: '/finance/transactions',
  path: '/finance/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancePaymentsRoute = AppFinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceInvoicesRoute = AppFinanceInvoicesRouteImport.update({
  id: '/finance/invoices',
  path: '/finance/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceExpensesRoute = AppFinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardHrRoute = AppDashboardHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardFinanceRoute = AppDashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardEmployeeRoute = AppDashboardEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardCrmRoute = AppDashboardCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppCrmTasksRoute = AppCrmTasksRouteImport.update({
  id: '/crm/tasks',
  path: '/crm/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmPipelineRoute = AppCrmPipelineRouteImport.update({
  id: '/crm/pipeline',
  path: '/crm/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmLeadsRoute = AppCrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCustomersRoute = AppCrmCustomersRouteImport.update({
  id: '/crm/customers',
  path: '/crm/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCountriesCategoriesRoute = AppCountriesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppCountriesRoute,
} as any)
const AppVisaApplicationsNewRoute = AppVisaApplicationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppVisaApplicationsRoute,
} as any)
const AppVisaApplicationsIdRoute = AppVisaApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVisaApplicationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/chat': typeof AppChatRoute
  '/countries': typeof AppCountriesRouteWithChildren
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/documents': typeof AppDocumentsRoute
  '/email': typeof AppEmailRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/countries/categories': typeof AppCountriesCategoriesRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/leads': typeof AppCrmLeadsRoute
  '/crm/pipeline': typeof AppCrmPipelineRoute
  '/crm/tasks': typeof AppCrmTasksRoute
  '/dashboard/crm': typeof AppDashboardCrmRoute
  '/dashboard/employee': typeof AppDashboardEmployeeRoute
  '/dashboard/finance': typeof AppDashboardFinanceRoute
  '/dashboard/hr': typeof AppDashboardHrRoute
  '/finance/expenses': typeof AppFinanceExpensesRoute
  '/finance/invoices': typeof AppFinanceInvoicesRoute
  '/finance/payments': typeof AppFinancePaymentsRoute
  '/finance/transactions': typeof AppFinanceTransactionsRoute
  '/hr/attendance': typeof AppHrAttendanceRoute
  '/hr/departments': typeof AppHrDepartmentsRoute
  '/hr/employees': typeof AppHrEmployeesRoute
  '/hr/leave': typeof AppHrLeaveRoute
  '/hr/payroll': typeof AppHrPayrollRoute
  '/settings/api': typeof AppSettingsApiRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/tasks/approvals': typeof AppTasksApprovalsRoute
  '/tasks/board': typeof AppTasksBoardRoute
  '/tasks/workflows': typeof AppTasksWorkflowsRoute
  '/visa/applications': typeof AppVisaApplicationsRouteWithChildren
  '/visa/approvals': typeof AppVisaApprovalsRoute
  '/visa/applications/$id': typeof AppVisaApplicationsIdRoute
  '/visa/applications/new': typeof AppVisaApplicationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/chat': typeof AppChatRoute
  '/countries': typeof AppCountriesRouteWithChildren
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/documents': typeof AppDocumentsRoute
  '/email': typeof AppEmailRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/countries/categories': typeof AppCountriesCategoriesRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/leads': typeof AppCrmLeadsRoute
  '/crm/pipeline': typeof AppCrmPipelineRoute
  '/crm/tasks': typeof AppCrmTasksRoute
  '/dashboard/crm': typeof AppDashboardCrmRoute
  '/dashboard/employee': typeof AppDashboardEmployeeRoute
  '/dashboard/finance': typeof AppDashboardFinanceRoute
  '/dashboard/hr': typeof AppDashboardHrRoute
  '/finance/expenses': typeof AppFinanceExpensesRoute
  '/finance/invoices': typeof AppFinanceInvoicesRoute
  '/finance/payments': typeof AppFinancePaymentsRoute
  '/finance/transactions': typeof AppFinanceTransactionsRoute
  '/hr/attendance': typeof AppHrAttendanceRoute
  '/hr/departments': typeof AppHrDepartmentsRoute
  '/hr/employees': typeof AppHrEmployeesRoute
  '/hr/leave': typeof AppHrLeaveRoute
  '/hr/payroll': typeof AppHrPayrollRoute
  '/settings/api': typeof AppSettingsApiRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/tasks/approvals': typeof AppTasksApprovalsRoute
  '/tasks/board': typeof AppTasksBoardRoute
  '/tasks/workflows': typeof AppTasksWorkflowsRoute
  '/visa/applications': typeof AppVisaApplicationsRouteWithChildren
  '/visa/approvals': typeof AppVisaApprovalsRoute
  '/visa/applications/$id': typeof AppVisaApplicationsIdRoute
  '/visa/applications/new': typeof AppVisaApplicationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/countries': typeof AppCountriesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/email': typeof AppEmailRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/countries/categories': typeof AppCountriesCategoriesRoute
  '/_app/crm/customers': typeof AppCrmCustomersRoute
  '/_app/crm/leads': typeof AppCrmLeadsRoute
  '/_app/crm/pipeline': typeof AppCrmPipelineRoute
  '/_app/crm/tasks': typeof AppCrmTasksRoute
  '/_app/dashboard/crm': typeof AppDashboardCrmRoute
  '/_app/dashboard/employee': typeof AppDashboardEmployeeRoute
  '/_app/dashboard/finance': typeof AppDashboardFinanceRoute
  '/_app/dashboard/hr': typeof AppDashboardHrRoute
  '/_app/finance/expenses': typeof AppFinanceExpensesRoute
  '/_app/finance/invoices': typeof AppFinanceInvoicesRoute
  '/_app/finance/payments': typeof AppFinancePaymentsRoute
  '/_app/finance/transactions': typeof AppFinanceTransactionsRoute
  '/_app/hr/attendance': typeof AppHrAttendanceRoute
  '/_app/hr/departments': typeof AppHrDepartmentsRoute
  '/_app/hr/employees': typeof AppHrEmployeesRoute
  '/_app/hr/leave': typeof AppHrLeaveRoute
  '/_app/hr/payroll': typeof AppHrPayrollRoute
  '/_app/settings/api': typeof AppSettingsApiRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/tasks/approvals': typeof AppTasksApprovalsRoute
  '/_app/tasks/board': typeof AppTasksBoardRoute
  '/_app/tasks/workflows': typeof AppTasksWorkflowsRoute
  '/_app/visa/applications': typeof AppVisaApplicationsRouteWithChildren
  '/_app/visa/approvals': typeof AppVisaApprovalsRoute
  '/_app/visa/applications/$id': typeof AppVisaApplicationsIdRoute
  '/_app/visa/applications/new': typeof AppVisaApplicationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/announcements'
    | '/chat'
    | '/countries'
    | '/dashboard'
    | '/documents'
    | '/email'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/countries/categories'
    | '/crm/customers'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/crm/tasks'
    | '/dashboard/crm'
    | '/dashboard/employee'
    | '/dashboard/finance'
    | '/dashboard/hr'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/transactions'
    | '/hr/attendance'
    | '/hr/departments'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/payroll'
    | '/settings/api'
    | '/settings/audit'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/users'
    | '/tasks/approvals'
    | '/tasks/board'
    | '/tasks/workflows'
    | '/visa/applications'
    | '/visa/approvals'
    | '/visa/applications/$id'
    | '/visa/applications/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/announcements'
    | '/chat'
    | '/countries'
    | '/dashboard'
    | '/documents'
    | '/email'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/countries/categories'
    | '/crm/customers'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/crm/tasks'
    | '/dashboard/crm'
    | '/dashboard/employee'
    | '/dashboard/finance'
    | '/dashboard/hr'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/transactions'
    | '/hr/attendance'
    | '/hr/departments'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/payroll'
    | '/settings/api'
    | '/settings/audit'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/users'
    | '/tasks/approvals'
    | '/tasks/board'
    | '/tasks/workflows'
    | '/visa/applications'
    | '/visa/approvals'
    | '/visa/applications/$id'
    | '/visa/applications/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/_app/announcements'
    | '/_app/chat'
    | '/_app/countries'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/email'
    | '/_app/notifications'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/countries/categories'
    | '/_app/crm/customers'
    | '/_app/crm/leads'
    | '/_app/crm/pipeline'
    | '/_app/crm/tasks'
    | '/_app/dashboard/crm'
    | '/_app/dashboard/employee'
    | '/_app/dashboard/finance'
    | '/_app/dashboard/hr'
    | '/_app/finance/expenses'
    | '/_app/finance/invoices'
    | '/_app/finance/payments'
    | '/_app/finance/transactions'
    | '/_app/hr/attendance'
    | '/_app/hr/departments'
    | '/_app/hr/employees'
    | '/_app/hr/leave'
    | '/_app/hr/payroll'
    | '/_app/settings/api'
    | '/_app/settings/audit'
    | '/_app/settings/roles'
    | '/_app/settings/security'
    | '/_app/settings/users'
    | '/_app/tasks/approvals'
    | '/_app/tasks/board'
    | '/_app/tasks/workflows'
    | '/_app/visa/applications'
    | '/_app/visa/approvals'
    | '/_app/visa/applications/$id'
    | '/_app/visa/applications/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email': {
      id: '/_app/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/countries': {
      id: '/_app/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof AppCountriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visa/approvals': {
      id: '/_app/visa/approvals'
      path: '/visa/approvals'
      fullPath: '/visa/approvals'
      preLoaderRoute: typeof AppVisaApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visa/applications': {
      id: '/_app/visa/applications'
      path: '/visa/applications'
      fullPath: '/visa/applications'
      preLoaderRoute: typeof AppVisaApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/workflows': {
      id: '/_app/tasks/workflows'
      path: '/tasks/workflows'
      fullPath: '/tasks/workflows'
      preLoaderRoute: typeof AppTasksWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/board': {
      id: '/_app/tasks/board'
      path: '/tasks/board'
      fullPath: '/tasks/board'
      preLoaderRoute: typeof AppTasksBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/approvals': {
      id: '/_app/tasks/approvals'
      path: '/tasks/approvals'
      fullPath: '/tasks/approvals'
      preLoaderRoute: typeof AppTasksApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/api': {
      id: '/_app/settings/api'
      path: '/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof AppSettingsApiRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/hr/payroll': {
      id: '/_app/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AppHrPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/leave': {
      id: '/_app/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof AppHrLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/employees': {
      id: '/_app/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AppHrEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/departments': {
      id: '/_app/hr/departments'
      path: '/hr/departments'
      fullPath: '/hr/departments'
      preLoaderRoute: typeof AppHrDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/attendance': {
      id: '/_app/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AppHrAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/transactions': {
      id: '/_app/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof AppFinanceTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/payments': {
      id: '/_app/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof AppFinancePaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/invoices': {
      id: '/_app/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AppFinanceInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/expenses': {
      id: '/_app/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AppFinanceExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/hr': {
      id: '/_app/dashboard/hr'
      path: '/hr'
      fullPath: '/dashboard/hr'
      preLoaderRoute: typeof AppDashboardHrRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/finance': {
      id: '/_app/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof AppDashboardFinanceRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/employee': {
      id: '/_app/dashboard/employee'
      path: '/employee'
      fullPath: '/dashboard/employee'
      preLoaderRoute: typeof AppDashboardEmployeeRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/crm': {
      id: '/_app/dashboard/crm'
      path: '/crm'
      fullPath: '/dashboard/crm'
      preLoaderRoute: typeof AppDashboardCrmRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/crm/tasks': {
      id: '/_app/crm/tasks'
      path: '/crm/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof AppCrmTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/pipeline': {
      id: '/_app/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof AppCrmPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/leads': {
      id: '/_app/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AppCrmLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/customers': {
      id: '/_app/crm/customers'
      path: '/crm/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof AppCrmCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/countries/categories': {
      id: '/_app/countries/categories'
      path: '/categories'
      fullPath: '/countries/categories'
      preLoaderRoute: typeof AppCountriesCategoriesRouteImport
      parentRoute: typeof AppCountriesRoute
    }
    '/_app/visa/applications/new': {
      id: '/_app/visa/applications/new'
      path: '/new'
      fullPath: '/visa/applications/new'
      preLoaderRoute: typeof AppVisaApplicationsNewRouteImport
      parentRoute: typeof AppVisaApplicationsRoute
    }
    '/_app/visa/applications/$id': {
      id: '/_app/visa/applications/$id'
      path: '/$id'
      fullPath: '/visa/applications/$id'
      preLoaderRoute: typeof AppVisaApplicationsIdRouteImport
      parentRoute: typeof AppVisaApplicationsRoute
    }
  }
}

interface AppCountriesRouteChildren {
  AppCountriesCategoriesRoute: typeof AppCountriesCategoriesRoute
}

const AppCountriesRouteChildren: AppCountriesRouteChildren = {
  AppCountriesCategoriesRoute: AppCountriesCategoriesRoute,
}

const AppCountriesRouteWithChildren = AppCountriesRoute._addFileChildren(
  AppCountriesRouteChildren,
)

interface AppDashboardRouteChildren {
  AppDashboardCrmRoute: typeof AppDashboardCrmRoute
  AppDashboardEmployeeRoute: typeof AppDashboardEmployeeRoute
  AppDashboardFinanceRoute: typeof AppDashboardFinanceRoute
  AppDashboardHrRoute: typeof AppDashboardHrRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardCrmRoute: AppDashboardCrmRoute,
  AppDashboardEmployeeRoute: AppDashboardEmployeeRoute,
  AppDashboardFinanceRoute: AppDashboardFinanceRoute,
  AppDashboardHrRoute: AppDashboardHrRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsApiRoute: typeof AppSettingsApiRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsApiRoute: AppSettingsApiRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppVisaApplicationsRouteChildren {
  AppVisaApplicationsIdRoute: typeof AppVisaApplicationsIdRoute
  AppVisaApplicationsNewRoute: typeof AppVisaApplicationsNewRoute
}

const AppVisaApplicationsRouteChildren: AppVisaApplicationsRouteChildren = {
  AppVisaApplicationsIdRoute: AppVisaApplicationsIdRoute,
  AppVisaApplicationsNewRoute: AppVisaApplicationsNewRoute,
}

const AppVisaApplicationsRouteWithChildren =
  AppVisaApplicationsRoute._addFileChildren(AppVisaApplicationsRouteChildren)

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppChatRoute: typeof AppChatRoute
  AppCountriesRoute: typeof AppCountriesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmailRoute: typeof AppEmailRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppCrmCustomersRoute: typeof AppCrmCustomersRoute
  AppCrmLeadsRoute: typeof AppCrmLeadsRoute
  AppCrmPipelineRoute: typeof AppCrmPipelineRoute
  AppCrmTasksRoute: typeof AppCrmTasksRoute
  AppFinanceExpensesRoute: typeof AppFinanceExpensesRoute
  AppFinanceInvoicesRoute: typeof AppFinanceInvoicesRoute
  AppFinancePaymentsRoute: typeof AppFinancePaymentsRoute
  AppFinanceTransactionsRoute: typeof AppFinanceTransactionsRoute
  AppHrAttendanceRoute: typeof AppHrAttendanceRoute
  AppHrDepartmentsRoute: typeof AppHrDepartmentsRoute
  AppHrEmployeesRoute: typeof AppHrEmployeesRoute
  AppHrLeaveRoute: typeof AppHrLeaveRoute
  AppHrPayrollRoute: typeof AppHrPayrollRoute
  AppTasksApprovalsRoute: typeof AppTasksApprovalsRoute
  AppTasksBoardRoute: typeof AppTasksBoardRoute
  AppTasksWorkflowsRoute: typeof AppTasksWorkflowsRoute
  AppVisaApplicationsRoute: typeof AppVisaApplicationsRouteWithChildren
  AppVisaApprovalsRoute: typeof AppVisaApprovalsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppChatRoute: AppChatRoute,
  AppCountriesRoute: AppCountriesRouteWithChildren,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmailRoute: AppEmailRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppCrmCustomersRoute: AppCrmCustomersRoute,
  AppCrmLeadsRoute: AppCrmLeadsRoute,
  AppCrmPipelineRoute: AppCrmPipelineRoute,
  AppCrmTasksRoute: AppCrmTasksRoute,
  AppFinanceExpensesRoute: AppFinanceExpensesRoute,
  AppFinanceInvoicesRoute: AppFinanceInvoicesRoute,
  AppFinancePaymentsRoute: AppFinancePaymentsRoute,
  AppFinanceTransactionsRoute: AppFinanceTransactionsRoute,
  AppHrAttendanceRoute: AppHrAttendanceRoute,
  AppHrDepartmentsRoute: AppHrDepartmentsRoute,
  AppHrEmployeesRoute: AppHrEmployeesRoute,
  AppHrLeaveRoute: AppHrLeaveRoute,
  AppHrPayrollRoute: AppHrPayrollRoute,
  AppTasksApprovalsRoute: AppTasksApprovalsRoute,
  AppTasksBoardRoute: AppTasksBoardRoute,
  AppTasksWorkflowsRoute: AppTasksWorkflowsRoute,
  AppVisaApplicationsRoute: AppVisaApplicationsRouteWithChildren,
  AppVisaApprovalsRoute: AppVisaApprovalsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionExpiredRoute: SessionExpiredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
